config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resources :rooms do
    resources :messages
  end

  root 'pages#home'

  devise_for :users
  get "user/:id", to: "users#show", as: "user"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit {broadcast_append_to self.room}
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private
    
    is_participant = Participant.where(user_id: self.user_id, room_id: self.room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> {where(is_private: false)}
  after_create_commit { broadcast_if_public }
  has_many :messages
  has_many :participants, dependent: :destroy

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  # Stops showing own name on list of logged-in users
  scope :all_except, -> (user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages
  belongs_to :role

  # this should be whatever the role_id for admin would be (in this case, 2)
  # this saves on queries
  def admin?
    self.role_id == 2
  end

  def staff?
    self.role_id == 2 || self.role_id == 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  include Pagy::Backend
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end

  private
  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :index_setup, only: [:index, :show]

  def index
  end

  def show
    @single_room = Room.find(params[:id]) if params[:id]

    authorize @single_room

    @message = Message.new
    message_query = @single_room.messages.order(created_at: :desc)
    @pagy, messages = pagy(message_query, items: 50)
    @messages = messages.reverse
  end

  def create
    @room = Room.create(room_params)
  end

  private
  def room_params
    params.require(:room).permit(:name)
  end

  def index_setup
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    authorize @single_room

    @message = Message.new
    message_query = @single_room.messages.order(created_at: :desc)
    @pagy, messages = pagy(message_query, items: 50)
    @messages = messages.reverse
  end

  private
  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/messages_helper.rb
module MessagesHelper
  def markdown(text)
    options = {
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      superscript: true,
      strikethrough: true,
      underline: true
    }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    sanitize(markdown.render(text))
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-fuchsia-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="<%= root_path  %>" class="flex items-center">
        <img src="<%= image_path("logo.webp") %>" class="h-8 mr-3" alt="Logo" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">TurboChat</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-fuchsia-900 dark:border-gray-700">
        <li>
          <a href="<%= root_path  %>" class="block py-2 pl-3 pr-4 text-fuchsia-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-700 md:p-0 dark:text-white md:dark:hover:text-fuchsia-300 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Home</a>
        </li>
        <li>
          <a href="#" class="block py-2 pl-3 pr-4 text-fuchsia-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-700 md:p-0 dark:text-white md:dark:hover:text-fuchsia-300 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Account</a>
        </li>
        <li>
          <a href="<%= rooms_path  %>" class="block py-2 pl-3 pr-4 text-fuchsia-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-700 md:p-0 dark:text-white md:dark:hover:text-fuchsia-300 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Rooms</a>
        </li>
        <li>
          <a href="#" class="block py-2 pl-3 pr-4 text-fuchsia-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-700 md:p-0 dark:text-white md:dark:hover:text-fuchsia-300 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Settings</a>
        </li>
        <li>
          <% if current_user %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"block py-2 pl-3 pr-4 text-fuchsia-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-700 md:p-0 dark:text-white md:dark:hover:text-fuchsia-300 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          <% else %>
          <%= link_to "Login", new_user_session_path, class:"block py-2 pl-3 pr-4 text-fuchsia-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-700 md:p-0 dark:text-white md:dark:hover:text-fuchsia-300 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_warnings.html.erb
<div class="text-center">
  <% if notice %>
  <div class="flex p-4 mb-4 text-sm text-blue-800 border border-blue-300 rounded-lg bg-blue-50 dark:text-blue-400 dark:border-blue-800" role="alert">
    <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
    <span class="sr-only">Info</span>
    <div>
      <%= notice if notice %>
    </div>
  </div>
  <% end %>
  <% if alert %>
  <div class="flex p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:text-red-400 dark:border-red-800" role="alert">
    <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
    <span class="sr-only">Info</span>
    <div>
      <%= alert if alert %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="">
    <%= render "layouts/navbar" %>
    <main class="container flex flex-col mx-0 max-w-full max-h-full h-[calc(100vh-64px)]">
      <%= render "layouts/warnings" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="flex flex-row m-1 group">
  <span class="opacity-0 group-hover:opacity-100 text-sm text-justify font-mono"><%= message.updated_at.in_time_zone('Central Time (US & Canada)').strftime("%T") %>&nbsp;</span>
  <span class="name underline font-bold"><%= link_to message.user.email, message.user %>&colon;</span>
  <p>&nbsp;<%= markdown(message.body) %></p>
</div>

app/views/messages/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with model: [@single_room, @message], remote: true, class: "flex flex-row w-full", data: { controller:"reset-form", action: "turbo:submit-end->reset-form#reset" }  do |f| %>
    <%= f.text_field :body, id: "chat-text", class:"w-full", autocomplete: "off" %>
    <%= f.submit data: {disable_with: false}, class: "bg-fuchsia-400 hover:bg-fuchsia-500 text-fuchsia-700 font-semibold hover:text-white py-2 px-4 border border-fuchsia-500 hover:border-transparent rounded max-w-48" %>
  <% end %>
</div>

app/views/messages/_pager.html.erb
<div id="pager" class="min-w-full my-8 min-y-8 flex justify-center bg-red-500">
  <div>
    <% if pagy.next %>
      <%= link_to(
        "Load more messages",
        room_path(page: pagy.next),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_stream: "",
          controller: "autoclick"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/messages/_pager_room.html.erb
<div id="pager" class="flex justify-center">
  <div>
    <% if pagy.next %>
      <%= link_to(
        "Load more messages",
        room_path(page: pagy.next),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_stream: "",
          controller: "autoclick"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/messages/_pager_user.html.erb
<div id="pager" class="flex justify-center">
  <div>
    <% if pagy.next %>
      <%= link_to(
        "Load more messages",
        user_path(page: pagy.next),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_stream: "",
          controller: "autoclick"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="text-center mx-auto">
  <h1 class="font-bold text-4xl">Turbochat Home</h1>
</div>

<div class="text-center flex flex-col mx-auto">
  <% if current_user %>
    <%= link_to "Start Chatting", rooms_path, class:"bg-fuchsia-500 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded w-36 text-center m-1" %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"bg-fuchsia-500 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded w-36 text-center m-1" %>
  <% else %>
    <%= link_to "Login", new_user_session_path, class:"bg-fuchsia-500 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded w-36 text-center m-1" %>
    <%= link_to "Sign Up", new_user_registration_path, class:"bg-fuchsia-500 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded w-36 text-center m-1" %>
  <% end %>
</div>

app/views/rooms/_new_room_form.html.erb
<%= form_with model: @room, remote: true, class: "", data: { controller:"reset-form", action: "turbo:submit-end->reset-form#reset" } do |f| %>
  <%= f.text_field :name, class: "w-1/2" , autocomplete: "off" %>
  <%= f.submit data:{disable_with: false}, class: "text-black bg-transparent hover:bg-fuchsia-500 text-fuchsia-700 font-semibold hover:text-white py-2 px-4 border border-fuchsia-500 hover:border-transparent rounded" %>
<% end %>

app/views/rooms/_room.html.erb
<div>
  <%= link_to room.name, room, data:{ turbo_frame: "room_container", turbo_action: "advance" } %>
</div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="container flex flex-row max-w-full h-full">
  
  <div id="side_panel", class="flex-col w-1/5 bg-gray-200 p-4">
    <h5 class="text-2xl font-bold"><%= current_user.email %></h5>
    <h4 class="text-2xl font-semibold">Users</h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>
    <h4 class="text-2xl font-semibold">Rooms</h4>
    <%= render "rooms/new_room_form" %>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <%= render @rooms %>
    </div>
  </div>

  <%= turbo_frame_tag "room_container", class:"bg-gray-800 max-w-full mx-auto w-4/5" do %>
  <% end %>

</div>

app/views/rooms/show.html.erb
<div id="chatroom_container" class="container flex flex-row max-w-full h-full">
  
  <div id="side_panel", class="flex-col w-1/5 bg-gray-200 p-4">
    <h5 class="text-2xl font-bold"><%= current_user.email %></h5>
    <h4 class="text-2xl font-semibold">Users</h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>
    <h4 class="text-2xl font-semibold">Rooms</h4>
    <%= render "rooms/new_room_form" %>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <%= render @rooms %>
    </div>
  </div>

  <%= turbo_frame_tag "room_container", class:"bg-gray-800 max-w-full mx-auto w-4/5" do%>
  <div id="single_room" class="flex flex-col content-end h-full">
    <div class="text-center shadow-xl bg-gray-500 border-black border-solid"><h3 class="text-2xl text-black font-bold"><%= @single_room.name %></h3></div>
    <%= turbo_stream_from @single_room %>
    <div id="messages" class="overflow-y-scroll h-full text-white", data-controller="scroll">
      <%= turbo_frame_tag "page_handler" %>
      <%= render "messages/pager_room", pagy: @pagy %>
      <div id="messages-container">
        <%= render @messages %>
      </div>
    </div>
    <%= render "messages/new_message_form" %>
  <div>
<% end %>

</div>

app/views/rooms/show.turbo_stream.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
    "prepend",
    target: "messages-container",
    template: %(#{render @messages})
    ) %>
  <%= turbo_stream_action_tag(
    "replace",
    target: "pager",
    template: %(#{render "messages/pager", pagy: @pagy})
    ) %>
<% end %>

app/views/users/_user.html.erb
<div>
  <%= link_to user.email, user, data:{ turbo_frame: "room_container", turbo_action: "advance" } %>
</div>

app/views/users/show.html.erb
<div id="chatroom_container" class="container flex flex-row max-w-full h-full">
  
  <div id="side_panel", class="flex-col w-1/5 bg-gray-200 p-4">
    <h5 class="text-2xl font-bold"><%= current_user.email %></h5>
    <h4 class="text-2xl font-semibold">Users</h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>
    <h4 class="text-2xl font-semibold">Rooms</h4>
    <%= render "rooms/new_room_form" %>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <%= render @rooms %>
    </div>
  </div>

  <%= turbo_frame_tag "room_container", class:"bg-gray-800 max-w-full mx-auto w-4/5" do%>
  <div id="single_room" class="flex flex-col content-end h-full">
    <div class="text-center shadow-xl bg-gray-500 border-black border-solid"><h3 class="text-2xl text-black font-bold"><%= @user.email %></h3></div>
    <%= turbo_stream_from @single_room %>
    <div id="messages" class="overflow-y-scroll h-full text-white", data-controller="scroll">
      <%= turbo_frame_tag "page_handler" %>
      <%= render "messages/pager_user", pagy: @pagy, room: @single_room %>
      <div id="messages-container">
        <%= render @messages %>
      </div>
    </div>
    <%= render "messages/new_message_form" %>
  <div>
<% end %>

</div>

app/views/users/show.turbo_stream.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
    "prepend",
    target: "messages-container",
    template: %(#{render @messages})
    ) %>
  <%= turbo_stream_action_tag(
    "replace",
    target: "pager",
    template: %(#{render "messages/pager_user", pagy: @pagy})
    ) %>
<% end %>